# Generated by Django 4.2.18 on 2025-02-03 06:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('role', models.CharField(default='guest', max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('village', models.CharField(max_length=30)),
                ('taluka', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=15)),
                ('experience_years', models.PositiveIntegerField()),
                ('aadhar_number', models.CharField(max_length=12)),
                ('type_of_driver', models.CharField(max_length=20)),
                ('images', models.JSONField(default={'Aadhar_image': '', 'DL_image': '', 'Driver_image': '', 'Vehicle_image': ''})),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jetship.guest')),
            ],
        ),
    ]
