# Generated by Django 4.2.18 on 2025-02-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetship', '0002_category_subcategory_alter_driver_images_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
